# Generated by Django 2.1.15 on 2024-03-26 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='player_role',
            new_name='player_profession',
        ),
    ]
